#!/usr/bin/env bash

set -e

keyfile=$(mktemp --suffix=.gpg)
trap "rm $keyfile" EXIT

curl --silent --show-error --fail \
    "https://neersighted.keybase.pub/keys/pgp.asc" \
| gpg --dearmor > $keyfile

curl --silent --show-error --fail \
    "https://neersighted.keybase.pub/keys/authorized_keys.asc" \
| gpgv --keyring $keyfile --output -
